### ISSUE TITLE
Did you manage to make this work with pyinstaller?

### ISSUE THREAD

**Issue by dev-namespace** [umlaeute/hy-test#1]
I can't manage to import hello after using pyinstaller on wrapper.py

> Traceback (most recent call last):
>   File "wrapper.py", line 5, in <module>
> ModuleNotFoundError: No module named 'hello'
> [17960] Failed to execute script wrapper

**Comment by umlaeute** [comment]
that's probably just a Python2 vs Python3 glitch.

a real-world, known-to-work example where i use `pyinstaller` for packaging a `hy`-application is [deken](/pure-data/deken) (see [developer/deken.spec](https://github.com/pure-data/deken/blob/master/developer/deken.spec)).
